// SYNTAX TEST "Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax"

// Licensed under the Apache License, Version 2.0 (the “License”); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an “AS IS” BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

   let {[key]:a=0,...b=0} = {a:1};
// ^^^ keyword.declaration.variable.js.fjsx15
//     ^ destructuring.object.js.fjsx15
//     ^ punctuation.delimiter.object.begin.js.fjsx15
//      ^ destructuring.object.js.fjsx15
//      ^ keyword.operator.other.computed-property.begin.js.fjsx15
//       ^^^ entity.name.variable.js.fjsx15
//          ^ destructuring.object.js.fjsx15
//          ^ keyword.operator.other.computed-property.end.js.fjsx15
//           ^ destructuring.object.js.fjsx15
//           ^ keyword.operator.other.association.js.fjsx15
//            ^ entity.name.variable.js.fjsx15
//             ^ keyword.operator.other.assignment.js.fjsx15
//              ^ constant.numeric.decimal.js.fjsx15
//               ^ destructuring.object.js.fjsx15
//               ^ punctuation.delimiter.object.js.fjsx15
//                ^^^ keyword.operator.other.rest.js.fjsx15
//                   ^ entity.name.variable.js.fjsx15
//                    ^ keyword.operator.other.assignment.js.fjsx15
//                     ^ constant.numeric.decimal.js.fjsx15
//                      ^ destructuring.object.js.fjsx15
//                      ^ punctuation.delimiter.object.end.js.fjsx15
//                        ^ keyword.operator.other.assignment.js.fjsx15
//                          ^ punctuation.delimiter.object.begin.js.fjsx15
//                           ^ object.property.js.fjsx15
//                           ^ entity.name.variable.js.fjsx15
//                            ^ object.js.fjsx15
//                            ^ keyword.operator.other.association.js.fjsx15
//                             ^ constant.numeric.decimal.js.fjsx15
//                              ^ punctuation.delimiter.object.end.js.fjsx15
//                               ^ keyword.operator.other.terminator.js.fjsx15
   let {a=0,...b=0} = {a:1,b:2};
// ^^^ keyword.declaration.variable.js.fjsx15
//     ^ destructuring.object.js.fjsx15
//     ^ punctuation.delimiter.object.begin.js.fjsx15
//      ^ entity.name.variable.js.fjsx15
//       ^ keyword.operator.other.assignment.js.fjsx15
//        ^ constant.numeric.decimal.js.fjsx15
//         ^ destructuring.object.js.fjsx15
//         ^ punctuation.delimiter.object.js.fjsx15
//          ^^^ keyword.operator.other.rest.js.fjsx15
//             ^ entity.name.variable.js.fjsx15
//              ^ keyword.operator.other.assignment.js.fjsx15
//               ^ constant.numeric.decimal.js.fjsx15
//                ^ destructuring.object.js.fjsx15
//                ^ punctuation.delimiter.object.end.js.fjsx15
//                  ^ keyword.operator.other.assignment.js.fjsx15
//                    ^ punctuation.delimiter.object.begin.js.fjsx15
//                     ^ object.property.js.fjsx15
//                     ^ entity.name.variable.js.fjsx15
//                      ^ object.js.fjsx15
//                      ^ keyword.operator.other.association.js.fjsx15
//                       ^ constant.numeric.decimal.js.fjsx15
//                        ^ punctuation.delimiter.object.js.fjsx15
//                         ^ object.property.js.fjsx15
//                         ^ entity.name.variable.js.fjsx15
//                          ^ object.js.fjsx15
//                          ^ keyword.operator.other.association.js.fjsx15
//                           ^ constant.numeric.decimal.js.fjsx15
//                            ^ punctuation.delimiter.object.end.js.fjsx15
//                             ^ keyword.operator.other.terminator.js.fjsx15
   let {a=0,...b=0}:{a:number,b:number} = {a:1,b:2};
// ^^^ keyword.declaration.variable.js.fjsx15
//     ^ destructuring.object.js.fjsx15
//     ^ punctuation.delimiter.object.begin.js.fjsx15
//      ^ entity.name.variable.js.fjsx15
//       ^ keyword.operator.other.assignment.js.fjsx15
//        ^ constant.numeric.decimal.js.fjsx15
//         ^ destructuring.object.js.fjsx15
//         ^ punctuation.delimiter.object.js.fjsx15
//          ^^^ keyword.operator.other.rest.js.fjsx15
//             ^ entity.name.variable.js.fjsx15
//              ^ keyword.operator.other.assignment.js.fjsx15
//               ^ constant.numeric.decimal.js.fjsx15
//                ^ destructuring.object.js.fjsx15
//                ^ punctuation.delimiter.object.end.js.fjsx15
//                 ^ keyword.operator.other.association.flowtype
//                  ^ punctuation.delimiter.object.begin.flowtype
//                     ^^^^^^ support.flowtype
//                     ^^^^^^ entity.name.type.flowtype
//                           ^ punctuation.delimiter.object.flowtype
//                              ^^^^^^ support.flowtype
//                              ^^^^^^ entity.name.type.flowtype
//                                    ^ punctuation.delimiter.object.end.flowtype
//                                      ^ keyword.operator.other.assignment.js.fjsx15
//                                        ^ punctuation.delimiter.object.begin.js.fjsx15
//                                           ^ constant.numeric.decimal.js.fjsx15
//                                            ^ punctuation.delimiter.object.js.fjsx15
//                                               ^ constant.numeric.decimal.js.fjsx15
//                                                ^ punctuation.delimiter.object.end.js.fjsx15
//                                                 ^ keyword.operator.other.terminator.js.fjsx15
   let {a:{a=0,...b=0}} = {a:{a:1,a:2}};
// ^^^ keyword.declaration.variable.js.fjsx15
//     ^ destructuring.object.js.fjsx15
//     ^ punctuation.delimiter.object.begin.js.fjsx15
//      ^ entity.name.variable.js.fjsx15
//       ^ destructuring.object.js.fjsx15
//       ^ keyword.operator.other.association.js.fjsx15
//        ^ destructuring.object.js.fjsx15
//        ^ punctuation.delimiter.object.begin.js.fjsx15
//         ^ entity.name.variable.js.fjsx15
//          ^ keyword.operator.other.assignment.js.fjsx15
//           ^ constant.numeric.decimal.js.fjsx15
//            ^ destructuring.object.js.fjsx15
//            ^ punctuation.delimiter.object.js.fjsx15
//             ^^^ keyword.operator.other.rest.js.fjsx15
//                ^ entity.name.variable.js.fjsx15
//                 ^ keyword.operator.other.assignment.js.fjsx15
//                  ^ constant.numeric.decimal.js.fjsx15
//                   ^ destructuring.object.js.fjsx15
//                   ^ punctuation.delimiter.object.end.js.fjsx15
//                    ^ destructuring.object.js.fjsx15
//                    ^ punctuation.delimiter.object.end.js.fjsx15
//                      ^ keyword.operator.other.assignment.js.fjsx15
//                        ^ punctuation.delimiter.object.begin.js.fjsx15
//                         ^ entity.name.variable.js.fjsx15
//                          ^ object.js.fjsx15
//                          ^ keyword.operator.other.association.js.fjsx15
//                           ^ punctuation.delimiter.object.begin.js.fjsx15
//                            ^ entity.name.variable.js.fjsx15
//                             ^ object.js.fjsx15
//                             ^ keyword.operator.other.association.js.fjsx15
//                              ^ constant.numeric.decimal.js.fjsx15
//                               ^ punctuation.delimiter.object.js.fjsx15
//                                ^ entity.name.variable.js.fjsx15
//                                 ^ object.js.fjsx15
//                                 ^ keyword.operator.other.association.js.fjsx15
//                                  ^ constant.numeric.decimal.js.fjsx15
//                                   ^ punctuation.delimiter.object.end.js.fjsx15
//                                    ^ punctuation.delimiter.object.end.js.fjsx15
//                                     ^ keyword.operator.other.terminator.js.fjsx15
   let {a:{a=0,...b=0}}:{a:{a:number,b:number}} = {a:{a:1,b:2}};
// ^^^ keyword.declaration.variable.js.fjsx15
//     ^ destructuring.object.js.fjsx15
//     ^ punctuation.delimiter.object.begin.js.fjsx15
//      ^ entity.name.variable.js.fjsx15
//       ^ destructuring.object.js.fjsx15
//       ^ keyword.operator.other.association.js.fjsx15
//        ^ destructuring.object.js.fjsx15
//        ^ punctuation.delimiter.object.begin.js.fjsx15
//         ^ entity.name.variable.js.fjsx15
//          ^ keyword.operator.other.assignment.js.fjsx15
//           ^ constant.numeric.decimal.js.fjsx15
//            ^ destructuring.object.js.fjsx15
//            ^ punctuation.delimiter.object.js.fjsx15
//             ^^^ keyword.operator.other.rest.js.fjsx15
//                ^ entity.name.variable.js.fjsx15
//                 ^ keyword.operator.other.assignment.js.fjsx15
//                  ^ constant.numeric.decimal.js.fjsx15
//                   ^ destructuring.object.js.fjsx15
//                   ^ punctuation.delimiter.object.end.js.fjsx15
//                    ^ destructuring.object.js.fjsx15
//                    ^ punctuation.delimiter.object.end.js.fjsx15
//                     ^ keyword.operator.other.association.flowtype
//                      ^ punctuation.delimiter.object.begin.flowtype
//                         ^ punctuation.delimiter.object.begin.flowtype
//                            ^^^^^^ support.flowtype
//                            ^^^^^^ entity.name.type.flowtype
//                                  ^ punctuation.delimiter.object.flowtype
//                                     ^^^^^^ support.flowtype
//                                     ^^^^^^ entity.name.type.flowtype
//                                           ^ punctuation.delimiter.object.end.flowtype
//                                            ^ punctuation.delimiter.object.end.flowtype
//                                              ^ keyword.operator.other.assignment.js.fjsx15
//                                                ^ punctuation.delimiter.object.begin.js.fjsx15
//                                                 ^ entity.name.variable.js.fjsx15
//                                                  ^ object.js.fjsx15
//                                                  ^ keyword.operator.other.association.js.fjsx15
//                                                   ^ punctuation.delimiter.object.begin.js.fjsx15
//                                                    ^ entity.name.variable.js.fjsx15
//                                                     ^ object.js.fjsx15
//                                                     ^ keyword.operator.other.association.js.fjsx15
//                                                      ^ constant.numeric.decimal.js.fjsx15
//                                                       ^ punctuation.delimiter.object.js.fjsx15
//                                                        ^ entity.name.variable.js.fjsx15
//                                                         ^ object.js.fjsx15
//                                                         ^ keyword.operator.other.association.js.fjsx15
//                                                          ^ constant.numeric.decimal.js.fjsx15
//                                                           ^ punctuation.delimiter.object.end.js.fjsx15
//                                                            ^ punctuation.delimiter.object.end.js.fjsx15
//                                                             ^ keyword.operator.other.terminator.js.fjsx15
    function foo({a=0,...b=0}){}
//  ^^^^^^^^ keyword.declaration.function.js.fjsx15
//           ^^^ entity.name.function.js.fjsx15
//              ^ punctuation.delimiter.function.parameters.begin.js.fjsx15
//               ^ destructuring.object.js.fjsx15
//               ^ punctuation.delimiter.object.begin.js.fjsx15
//                ^ entity.name.variable.js.fjsx15
//                 ^ keyword.operator.other.assignment.js.fjsx15
//                  ^ constant.numeric.decimal.js.fjsx15
//                   ^ destructuring.object.js.fjsx15
//                   ^ punctuation.delimiter.object.js.fjsx15
//                    ^^^ keyword.operator.other.rest.js.fjsx15
//                       ^ entity.name.variable.js.fjsx15
//                        ^ keyword.operator.other.assignment.js.fjsx15
//                         ^ constant.numeric.decimal.js.fjsx15
//                          ^ destructuring.object.js.fjsx15
//                          ^ punctuation.delimiter.object.end.js.fjsx15
//                           ^ punctuation.delimiter.function.parameters.end.js.fjsx15
//                            ^ punctuation.delimiter.function.body.begin.js.fjsx15
//                             ^ punctuation.delimiter.function.body.end.js.fjsx15
    function foo({a=0,...b=0}:{a:number,b:number}){}
//  ^^^^^^^^ keyword.declaration.function.js.fjsx15
//           ^^^ entity.name.function.js.fjsx15
//              ^ punctuation.delimiter.function.parameters.begin.js.fjsx15
//               ^ destructuring.object.js.fjsx15
//               ^ punctuation.delimiter.object.begin.js.fjsx15
//                ^ entity.name.variable.js.fjsx15
//                 ^ keyword.operator.other.assignment.js.fjsx15
//                  ^ constant.numeric.decimal.js.fjsx15
//                   ^ destructuring.object.js.fjsx15
//                   ^ punctuation.delimiter.object.js.fjsx15
//                    ^^^ keyword.operator.other.rest.js.fjsx15
//                       ^ entity.name.variable.js.fjsx15
//                        ^ keyword.operator.other.assignment.js.fjsx15
//                         ^ constant.numeric.decimal.js.fjsx15
//                          ^ destructuring.object.js.fjsx15
//                          ^ punctuation.delimiter.object.end.js.fjsx15
//                           ^ keyword.operator.other.association.flowtype
//                            ^ punctuation.delimiter.object.begin.flowtype
//                               ^^^^^^ support.flowtype
//                               ^^^^^^ entity.name.type.flowtype
//                                     ^ punctuation.delimiter.object.flowtype
//                                        ^^^^^^ support.flowtype
//                                        ^^^^^^ entity.name.type.flowtype
//                                              ^ punctuation.delimiter.object.end.flowtype
//                                               ^ punctuation.delimiter.function.parameters.end.js.fjsx15
//                                                ^ punctuation.delimiter.function.body.begin.js.fjsx15
//                                                 ^ punctuation.delimiter.function.body.end.js.fjsx15
    function foo({a:{a=0,...b=0}}){}
//  ^^^^^^^^ keyword.declaration.function.js.fjsx15
//           ^^^ entity.name.function.js.fjsx15
//              ^ punctuation.delimiter.function.parameters.begin.js.fjsx15
//               ^ destructuring.object.js.fjsx15
//               ^ punctuation.delimiter.object.begin.js.fjsx15
//                ^ entity.name.variable.js.fjsx15
//                 ^ destructuring.object.js.fjsx15
//                 ^ keyword.operator.other.association.js.fjsx15
//                  ^ destructuring.object.js.fjsx15
//                  ^ punctuation.delimiter.object.begin.js.fjsx15
//                   ^ entity.name.variable.js.fjsx15
//                    ^ keyword.operator.other.assignment.js.fjsx15
//                     ^ constant.numeric.decimal.js.fjsx15
//                      ^ destructuring.object.js.fjsx15
//                      ^ punctuation.delimiter.object.js.fjsx15
//                       ^^^ keyword.operator.other.rest.js.fjsx15
//                          ^ entity.name.variable.js.fjsx15
//                           ^ keyword.operator.other.assignment.js.fjsx15
//                            ^ constant.numeric.decimal.js.fjsx15
//                             ^ destructuring.object.js.fjsx15
//                             ^ punctuation.delimiter.object.end.js.fjsx15
//                              ^ destructuring.object.js.fjsx15
//                              ^ punctuation.delimiter.object.end.js.fjsx15
//                               ^ punctuation.delimiter.function.parameters.end.js.fjsx15
//                                ^ punctuation.delimiter.function.body.begin.js.fjsx15
//                                 ^ punctuation.delimiter.function.body.end.js.fjsx15
    function foo({a:{a=0,...b=0}}:{a:{a:number,b:number}}){}
//  ^^^^^^^^ keyword.declaration.function.js.fjsx15
//           ^^^ entity.name.function.js.fjsx15
//              ^ punctuation.delimiter.function.parameters.begin.js.fjsx15
//               ^ destructuring.object.js.fjsx15
//               ^ punctuation.delimiter.object.begin.js.fjsx15
//                ^ entity.name.variable.js.fjsx15
//                 ^ destructuring.object.js.fjsx15
//                 ^ keyword.operator.other.association.js.fjsx15
//                  ^ destructuring.object.js.fjsx15
//                  ^ punctuation.delimiter.object.begin.js.fjsx15
//                   ^ entity.name.variable.js.fjsx15
//                    ^ keyword.operator.other.assignment.js.fjsx15
//                     ^ constant.numeric.decimal.js.fjsx15
//                      ^ destructuring.object.js.fjsx15
//                      ^ punctuation.delimiter.object.js.fjsx15
//                       ^^^ keyword.operator.other.rest.js.fjsx15
//                          ^ entity.name.variable.js.fjsx15
//                           ^ keyword.operator.other.assignment.js.fjsx15
//                            ^ constant.numeric.decimal.js.fjsx15
//                             ^ destructuring.object.js.fjsx15
//                             ^ punctuation.delimiter.object.end.js.fjsx15
//                              ^ destructuring.object.js.fjsx15
//                              ^ punctuation.delimiter.object.end.js.fjsx15
//                               ^ keyword.operator.other.association.flowtype
//                                ^ punctuation.delimiter.object.begin.flowtype
//                                   ^ punctuation.delimiter.object.begin.flowtype
//                                      ^^^^^^ support.flowtype
//                                      ^^^^^^ entity.name.type.flowtype
//                                            ^ punctuation.delimiter.object.flowtype
//                                               ^^^^^^ support.flowtype
//                                               ^^^^^^ entity.name.type.flowtype
//                                                     ^ punctuation.delimiter.object.end.flowtype
//                                                      ^ punctuation.delimiter.object.end.flowtype
//                                                       ^ punctuation.delimiter.function.parameters.end.js.fjsx15
//                                                        ^ punctuation.delimiter.function.body.begin.js.fjsx15
//                                                         ^ punctuation.delimiter.function.body.end.js.fjsx15
