%YAML1.2
---

# Licensed under the Apache License, Version 2.0 (the “License”); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

contexts:
  main:
    - match: |
        (?x)\s*\b
        ((?> Chart
            (?> ApplyTemplate
              | Close
              | First
              | Get(?>Double|Integer|String)
              | ID
              | Indicator(?>Delete|Name|sTotal)
              | Navigate
              | Next
              | Open
              | Period
              | PriceOnDropped
              | Redraw
              | SaveTemplate
              | ScreenShot
              | Set(?>Double|Integer|String|SymbolPeriod)
              | Symbol
              | Time(?>OnDropped|PriceToXY)
              | Window(?>Find|OnDropped)
              | XOnDropped
              | XYToTimePrice
              | YOnDropped
            )
          | Period
          | Symbol
          | Window
            (?> BarsPerChart
              | ExpertName
              | Find
              | FirstVisibleBar
              | Handle
              | IsVisible
              | OnDropped
              | Price(?:Max|Min|OnDropped)
              | Redraw
              | ScreenShot
              | sTotal
              | TimeOnDropped
              | (?>X|Y)OnDropped
            )
        ))(?=\s*\()
      captures:
        1: >-
          support.mql.mql4
          entity.name.function.mql.mql4
      set: arguments

  arguments:
    - include: ~/mql/function-call/arguments
