// SYNTAX TEST "Packages/Naomi/syntaxes/naomi.mql4.sublime-syntax"

// Licensed under the Apache License, Version 2.0 (the “License”); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an “AS IS” BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

    #property strict
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^ entity.name.property.mql.mql4
    #property icon "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^ entity.name.property.mql.mql4
//                 ^^^^^ string.quoted.double.mql.mql4
//                  ^^^ string.content.mql.mql4
//                 ^ punctuation.definition.string.begin.mql.mql4
//                     ^ punctuation.definition.string.end.mql.mql4
    #property link "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^ entity.name.property.mql.mql4
//                 ^^^^^ string.quoted.double.mql.mql4
//                  ^^^ string.content.mql.mql4
//                 ^ punctuation.definition.string.begin.mql.mql4
//                     ^ punctuation.definition.string.end.mql.mql4
    #property copyright "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^ entity.name.property.mql.mql4
//                      ^^^^^ string.quoted.double.mql.mql4
//                       ^^^ string.content.mql.mql4
//                      ^ punctuation.definition.string.begin.mql.mql4
//                          ^ punctuation.definition.string.end.mql.mql4
    #property version "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^ entity.name.property.mql.mql4
//                    ^^^^^ string.quoted.double.mql.mql4
//                     ^^^ string.content.mql.mql4
//                    ^ punctuation.definition.string.begin.mql.mql4
//                        ^ punctuation.definition.string.end.mql.mql4
    #property description "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^ entity.name.property.mql.mql4
//                        ^^^^^ string.quoted.double.mql.mql4
//                         ^^^ string.content.mql.mql4
//                        ^ punctuation.definition.string.begin.mql.mql4
//                            ^ punctuation.definition.string.end.mql.mql4
    #property stacksize 1
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^ entity.name.property.mql.mql4
//                      ^ constant.numeric.decimal.mql.mql4
    #property library
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^ entity.name.property.mql.mql4
    #property indicator_chart_window
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
    #property indicator_separate_window
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
    #property indicator_height 1
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^ constant.numeric.decimal.mql.mql4
    #property indicator_buffers 1
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                              ^ constant.numeric.decimal.mql.mql4
    #property indicator_minimum 1.0
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                              ^^^ constant.numeric.float.mql.mql4
    #property indicator_maximum 1.0
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                              ^^^ constant.numeric.float.mql.mql4
    #property indicator_label1 "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^ string.quoted.double.mql.mql4
//                              ^^^ string.content.mql.mql4
//                             ^ punctuation.definition.string.begin.mql.mql4
//                                 ^ punctuation.definition.string.end.mql.mql4
    #property indicator_label2 "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^ string.quoted.double.mql.mql4
//                              ^^^ string.content.mql.mql4
//                             ^ punctuation.definition.string.begin.mql.mql4
//                                 ^ punctuation.definition.string.end.mql.mql4
    #property indicator_color1 C'42,42,42'
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^^^^^^^ constant.color.mql.mql4
//                               ^^ color.value.r.mql.mql4
//                                  ^^ color.value.g.mql.mql4
//                                     ^^ color.value.b.mql.mql4
//                             ^^ punctuation.definition.color.begin.mql.mql4
//                                 ^ punctuation.definition.color.mql.mql4
//                                    ^ punctuation.definition.color.mql.mql4
//                                       ^ punctuation.definition.color.end.mql.mql4
    #property indicator_color2 C'42,42,42'
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^^^^^^^ constant.color.mql.mql4
//                               ^^ color.value.r.mql.mql4
//                                  ^^ color.value.g.mql.mql4
//                                     ^^ color.value.b.mql.mql4
//                             ^^ punctuation.definition.color.begin.mql.mql4
//                                 ^ punctuation.definition.color.mql.mql4
//                                    ^ punctuation.definition.color.mql.mql4
//                                       ^ punctuation.definition.color.end.mql.mql4
    #property indicator_color1 C'0x42,0x42,0x42'
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^^^^^^^^^^^^^ constant.color.mql.mql4
//                               ^^^^ color.value.r.mql.mql4
//                                    ^^^^ color.value.g.mql.mql4
//                                         ^^^^ color.value.b.mql.mql4
//                             ^^ punctuation.definition.color.begin.mql.mql4
//                                   ^ punctuation.definition.color.mql.mql4
//                                        ^ punctuation.definition.color.mql.mql4
//                                             ^ punctuation.definition.color.end.mql.mql4
    #property indicator_color1 clrRed
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^^ support.mql.mql4
    #property indicator_width1 1
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^ constant.numeric.decimal.mql.mql4
    #property indicator_style1 1
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^ constant.numeric.decimal.mql.mql4
    #property indicator_style1 STYLE_SOLID
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^^^^^^^ support.mql.mql4
    #property indicator_levelcolor C'42,42,42'
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                                 ^^^^^^^^^^^ constant.color.mql.mql4
//                                   ^^ color.value.r.mql.mql4
//                                      ^^ color.value.g.mql.mql4
//                                         ^^ color.value.b.mql.mql4
//                                 ^^ punctuation.definition.color.begin.mql.mql4
//                                     ^ punctuation.definition.color.mql.mql4
//                                        ^ punctuation.definition.color.mql.mql4
//                                           ^ punctuation.definition.color.end.mql.mql4
    #property indicator_levelcolor C'0x42,0x42,0x42'
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                                 ^^^^^^^^^^^^^^^^^ constant.color.mql.mql4
//                                   ^^^^ color.value.r.mql.mql4
//                                        ^^^^ color.value.g.mql.mql4
//                                             ^^^^ color.value.b.mql.mql4
//                                 ^^ punctuation.definition.color.begin.mql.mql4
//                                       ^ punctuation.definition.color.mql.mql4
//                                            ^ punctuation.definition.color.mql.mql4
//                                                 ^ punctuation.definition.color.end.mql.mql4
    #property indicator_levelcolor clrRed
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                                 ^^^^^^ support.mql.mql4
    #property indicator_levelwidth 1
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                                 ^ constant.numeric.decimal.mql.mql4
    #property indicator_levelstyle 1
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                                 ^ constant.numeric.decimal.mql.mql4
    #property indicator_levelstyle STYLE_SOLID
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                                 ^^^^^^^^^^^ support.mql.mql4
    #property script_show_confirm
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
    #property script_show_inputs
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
    #property tester_file "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^ entity.name.property.mql.mql4
//                        ^^^^^ string.quoted.double.mql.mql4
//                         ^^^ string.content.mql.mql4
//                        ^ punctuation.definition.string.begin.mql.mql4
//                            ^ punctuation.definition.string.end.mql.mql4
    #property tester_indicator "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                             ^^^^^ string.quoted.double.mql.mql4
//                              ^^^ string.content.mql.mql4
//                             ^ punctuation.definition.string.begin.mql.mql4
//                                 ^ punctuation.definition.string.end.mql.mql4
    #property tester_library "..."
//  ^^^^^^^^^ keyword.preprocessor.mql.mql4
//            ^^^^^^^^^^^^^^ entity.name.property.mql.mql4
//                           ^^^^^ string.quoted.double.mql.mql4
//                            ^^^ string.content.mql.mql4
//                           ^ punctuation.definition.string.begin.mql.mql4
//                               ^ punctuation.definition.string.end.mql.mql4
